//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.13 at 03:04:49 PM GMT+05:30 
//


package org.apache.ivory.entity.v0.process;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import org.apache.ivory.entity.v0.Entity;


/**
 * <p>Java class for processType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="processType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="clusters" type="{}clustersType"/>
 *         &lt;element name="concurrency" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="execution" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="frequency" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="periodicity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="validity" type="{}validityType"/>
 *         &lt;element name="inputs" type="{}inputsType"/>
 *         &lt;element name="outputs" type="{}outputsType"/>
 *         &lt;element name="properties" type="{}propertiesType"/>
 *         &lt;element name="workflow" type="{}workflowType"/>
 *         &lt;element name="retry" type="{}retryType"/>
 *         &lt;element name="late-process" type="{}late-processType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{}IDENTIFIER" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "processType", propOrder = {
    "clusters",
    "concurrency",
    "execution",
    "frequency",
    "periodicity",
    "validity",
    "inputs",
    "outputs",
    "properties",
    "workflow",
    "retry",
    "lateProcess"
})
@XmlRootElement(name="process")
public class ProcessType extends Entity{

    @XmlElement(required = true)
    protected ClustersType clusters;
    @XmlElement(required = true)
    protected String concurrency;
    @XmlElement(required = true)
    protected String execution;
    @XmlElement(required = true)
    protected String frequency;
    @XmlElement(required = true)
    protected String periodicity;
    @XmlElement(required = true)
    protected ValidityType validity;
    @XmlElement(required = true)
    protected InputsType inputs;
    @XmlElement(required = true)
    protected OutputsType outputs;
    @XmlElement(required = true)
    protected PropertiesType properties;
    @XmlElement(required = true)
    protected WorkflowType workflow;
    @XmlElement(required = true)
    protected RetryType retry;
    @XmlElement(name = "late-process", required = true)
    protected LateProcessType lateProcess;
    @XmlAttribute
    protected String name;

    /**
     * Gets the value of the clusters property.
     * 
     * @return
     *     possible object is
     *     {@link ClustersType }
     *     
     */
    public ClustersType getClusters() {
        return clusters;
    }

    /**
     * Sets the value of the clusters property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClustersType }
     *     
     */
    public void setClusters(ClustersType value) {
        this.clusters = value;
    }

    /**
     * Gets the value of the concurrency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConcurrency() {
        return concurrency;
    }

    /**
     * Sets the value of the concurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConcurrency(String value) {
        this.concurrency = value;
    }

    /**
     * Gets the value of the execution property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExecution() {
        return execution;
    }

    /**
     * Sets the value of the execution property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExecution(String value) {
        this.execution = value;
    }

    /**
     * Gets the value of the frequency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrequency() {
        return frequency;
    }

    /**
     * Sets the value of the frequency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrequency(String value) {
        this.frequency = value;
    }

    /**
     * Gets the value of the periodicity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPeriodicity() {
        return periodicity;
    }

    /**
     * Sets the value of the periodicity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPeriodicity(String value) {
        this.periodicity = value;
    }

    /**
     * Gets the value of the validity property.
     * 
     * @return
     *     possible object is
     *     {@link ValidityType }
     *     
     */
    public ValidityType getValidity() {
        return validity;
    }

    /**
     * Sets the value of the validity property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValidityType }
     *     
     */
    public void setValidity(ValidityType value) {
        this.validity = value;
    }

    /**
     * Gets the value of the inputs property.
     * 
     * @return
     *     possible object is
     *     {@link InputsType }
     *     
     */
    public InputsType getInputs() {
        return inputs;
    }

    /**
     * Sets the value of the inputs property.
     * 
     * @param value
     *     allowed object is
     *     {@link InputsType }
     *     
     */
    public void setInputs(InputsType value) {
        this.inputs = value;
    }

    /**
     * Gets the value of the outputs property.
     * 
     * @return
     *     possible object is
     *     {@link OutputsType }
     *     
     */
    public OutputsType getOutputs() {
        return outputs;
    }

    /**
     * Sets the value of the outputs property.
     * 
     * @param value
     *     allowed object is
     *     {@link OutputsType }
     *     
     */
    public void setOutputs(OutputsType value) {
        this.outputs = value;
    }

    /**
     * Gets the value of the properties property.
     * 
     * @return
     *     possible object is
     *     {@link PropertiesType }
     *     
     */
    public PropertiesType getProperties() {
        return properties;
    }

    /**
     * Sets the value of the properties property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertiesType }
     *     
     */
    public void setProperties(PropertiesType value) {
        this.properties = value;
    }

    /**
     * Gets the value of the workflow property.
     * 
     * @return
     *     possible object is
     *     {@link WorkflowType }
     *     
     */
    public WorkflowType getWorkflow() {
        return workflow;
    }

    /**
     * Sets the value of the workflow property.
     * 
     * @param value
     *     allowed object is
     *     {@link WorkflowType }
     *     
     */
    public void setWorkflow(WorkflowType value) {
        this.workflow = value;
    }

    /**
     * Gets the value of the retry property.
     * 
     * @return
     *     possible object is
     *     {@link RetryType }
     *     
     */
    public RetryType getRetry() {
        return retry;
    }

    /**
     * Sets the value of the retry property.
     * 
     * @param value
     *     allowed object is
     *     {@link RetryType }
     *     
     */
    public void setRetry(RetryType value) {
        this.retry = value;
    }

    /**
     * Gets the value of the lateProcess property.
     * 
     * @return
     *     possible object is
     *     {@link LateProcessType }
     *     
     */
    public LateProcessType getLateProcess() {
        return lateProcess;
    }

    /**
     * Sets the value of the lateProcess property.
     * 
     * @param value
     *     allowed object is
     *     {@link LateProcessType }
     *     
     */
    public void setLateProcess(LateProcessType value) {
        this.lateProcess = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
        super.setName(value);
    }

}
