//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.19 at 11:26:05 AM GMT+05:30 
//


package org.apache.ivory.entity.v0.process;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import org.apache.ivory.entity.v0.Entity;


/**
 * <p>Java class for process complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="process">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="clusters" type="{}clusters"/>
 *         &lt;element name="concurrency" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="execution" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="frequency" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="periodicity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="validity" type="{}validity"/>
 *         &lt;element name="inputs" type="{}inputs"/>
 *         &lt;element name="outputs" type="{}outputs"/>
 *         &lt;element name="properties" type="{}properties"/>
 *         &lt;element name="workflow" type="{}workflow"/>
 *         &lt;element name="retry" type="{}retry"/>
 *         &lt;element name="late-process" type="{}late-process"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{}IDENTIFIER" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "process", propOrder = {
    "clusters",
    "concurrency",
    "execution",
    "frequency",
    "periodicity",
    "validity",
    "inputs",
    "outputs",
    "properties",
    "workflow",
    "retry",
    "lateProcess"
})
@XmlRootElement(name="process")
public class Process extends Entity{

    @XmlElement(required = true)
    protected Clusters clusters;
    @XmlElement(required = true)
    protected String concurrency;
    @XmlElement(required = true)
    protected String execution;
    @XmlElement(required = true)
    protected String frequency;
    @XmlElement(required = true)
    protected String periodicity;
    @XmlElement(required = true)
    protected Validity validity;
    @XmlElement(required = true)
    protected Inputs inputs;
    @XmlElement(required = true)
    protected Outputs outputs;
	//@XmlJavaTypeAdapter(PropertiesMapAdapter.class)
    @XmlElement(required = true)
    protected Properties properties;
    @XmlElement(required = true)
    protected Workflow workflow;
    @XmlElement(required = true)
    protected Retry retry;
    @XmlElement(name = "late-process", required = true)
    protected LateProcess lateProcess;
    @XmlAttribute
    protected String name;

    /**
     * Gets the value of the clusters property.
     * 
     * @return
     *     possible object is
     *     {@link Clusters }
     *     
     */
    public Clusters getClusters() {
        return clusters;
    }

    /**
     * Sets the value of the clusters property.
     * 
     * @param value
     *     allowed object is
     *     {@link Clusters }
     *     
     */
    public void setClusters(Clusters value) {
        this.clusters = value;
    }

    /**
     * Gets the value of the concurrency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConcurrency() {
        return concurrency;
    }

    /**
     * Sets the value of the concurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConcurrency(String value) {
        this.concurrency = value;
    }

    /**
     * Gets the value of the execution property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExecution() {
        return execution;
    }

    /**
     * Sets the value of the execution property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExecution(String value) {
        this.execution = value;
    }

    /**
     * Gets the value of the frequency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrequency() {
        return frequency;
    }

    /**
     * Sets the value of the frequency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrequency(String value) {
        this.frequency = value;
    }

    /**
     * Gets the value of the periodicity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPeriodicity() {
        return periodicity;
    }

    /**
     * Sets the value of the periodicity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPeriodicity(String value) {
        this.periodicity = value;
    }

    /**
     * Gets the value of the validity property.
     * 
     * @return
     *     possible object is
     *     {@link Validity }
     *     
     */
    public Validity getValidity() {
        return validity;
    }

    /**
     * Sets the value of the validity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Validity }
     *     
     */
    public void setValidity(Validity value) {
        this.validity = value;
    }

    /**
     * Gets the value of the inputs property.
     * 
     * @return
     *     possible object is
     *     {@link Inputs }
     *     
     */
    public Inputs getInputs() {
        return inputs;
    }

    /**
     * Sets the value of the inputs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Inputs }
     *     
     */
    public void setInputs(Inputs value) {
        this.inputs = value;
    }

    /**
     * Gets the value of the outputs property.
     * 
     * @return
     *     possible object is
     *     {@link Outputs }
     *     
     */
    public Outputs getOutputs() {
        return outputs;
    }

    /**
     * Sets the value of the outputs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Outputs }
     *     
     */
    public void setOutputs(Outputs value) {
        this.outputs = value;
    }

    /**
     * Gets the value of the properties property.
     * 
     * @return
     *     possible object is
     *     {@link Properties }
     *     
     */
    public Properties getProperties() {
        return properties;
    }

    /**
     * Sets the value of the properties property.
     * 
     * @param value
     *     allowed object is
     *     
     */
    public void setProperties(Properties value) {
        this.properties = value;
    }

    /**
     * Gets the value of the workflow property.
     * 
     * @return
     *     possible object is
     *     {@link Workflow }
     *     
     */
    public Workflow getWorkflow() {
        return workflow;
    }

    /**
     * Sets the value of the workflow property.
     * 
     * @param value
     *     allowed object is
     *     {@link Workflow }
     *     
     */
    public void setWorkflow(Workflow value) {
        this.workflow = value;
    }

    /**
     * Gets the value of the retry property.
     * 
     * @return
     *     possible object is
     *     {@link Retry }
     *     
     */
    public Retry getRetry() {
        return retry;
    }

    /**
     * Sets the value of the retry property.
     * 
     * @param value
     *     allowed object is
     *     {@link Retry }
     *     
     */
    public void setRetry(Retry value) {
        this.retry = value;
    }

    /**
     * Gets the value of the lateProcess property.
     * 
     * @return
     *     possible object is
     *     {@link LateProcess }
     *     
     */
    public LateProcess getLateProcess() {
        return lateProcess;
    }

    /**
     * Sets the value of the lateProcess property.
     * 
     * @param value
     *     allowed object is
     *     {@link LateProcess }
     *     
     */
    public void setLateProcess(LateProcess value) {
        this.lateProcess = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
