//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.27 at 05:15:54 PM GMT+05:30 
//


package org.apache.ivory.oozie.workflow;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ACTION complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ACTION">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="map-reduce" type="{uri:oozie:workflow:0.3}MAP-REDUCE"/>
 *           &lt;element name="pig" type="{uri:oozie:workflow:0.3}PIG"/>
 *           &lt;element name="sub-workflow" type="{uri:oozie:workflow:0.3}SUB-WORKFLOW"/>
 *           &lt;element name="fs" type="{uri:oozie:workflow:0.3}FS"/>
 *           &lt;element name="java" type="{uri:oozie:workflow:0.3}JAVA"/>
 *         &lt;/choice>
 *         &lt;element name="ok" type="{uri:oozie:workflow:0.3}ACTION_TRANSITION"/>
 *         &lt;element name="error" type="{uri:oozie:workflow:0.3}ACTION_TRANSITION"/>
 *         &lt;any namespace='uri:oozie:sla:0.1' minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{uri:oozie:workflow:0.3}IDENTIFIER" />
 *       &lt;attribute name="cred" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="retry-max" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="retry-interval" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ACTION", propOrder = {
    "mapReduce",
    "pig",
    "subWorkflow",
    "fs",
    "java",
    "ok",
    "error",
    "any"
})
public class ACTION {

    @XmlElement(name = "map-reduce")
    protected MAPREDUCE mapReduce;
    protected PIG pig;
    @XmlElement(name = "sub-workflow")
    protected SUBWORKFLOW subWorkflow;
    protected FS fs;
    protected JAVA java;
    @XmlElement(required = true)
    protected ACTIONTRANSITION ok;
    @XmlElement(required = true)
    protected ACTIONTRANSITION error;
    @XmlAnyElement(lax = true)
    protected Object any;
    @XmlAttribute(required = true)
    protected String name;
    @XmlAttribute
    protected String cred;
    @XmlAttribute(name = "retry-max")
    protected String retryMax;
    @XmlAttribute(name = "retry-interval")
    protected String retryInterval;

    /**
     * Gets the value of the mapReduce property.
     * 
     * @return
     *     possible object is
     *     {@link MAPREDUCE }
     *     
     */
    public MAPREDUCE getMapReduce() {
        return mapReduce;
    }

    /**
     * Sets the value of the mapReduce property.
     * 
     * @param value
     *     allowed object is
     *     {@link MAPREDUCE }
     *     
     */
    public void setMapReduce(MAPREDUCE value) {
        this.mapReduce = value;
    }

    /**
     * Gets the value of the pig property.
     * 
     * @return
     *     possible object is
     *     {@link PIG }
     *     
     */
    public PIG getPig() {
        return pig;
    }

    /**
     * Sets the value of the pig property.
     * 
     * @param value
     *     allowed object is
     *     {@link PIG }
     *     
     */
    public void setPig(PIG value) {
        this.pig = value;
    }

    /**
     * Gets the value of the subWorkflow property.
     * 
     * @return
     *     possible object is
     *     {@link SUBWORKFLOW }
     *     
     */
    public SUBWORKFLOW getSubWorkflow() {
        return subWorkflow;
    }

    /**
     * Sets the value of the subWorkflow property.
     * 
     * @param value
     *     allowed object is
     *     {@link SUBWORKFLOW }
     *     
     */
    public void setSubWorkflow(SUBWORKFLOW value) {
        this.subWorkflow = value;
    }

    /**
     * Gets the value of the fs property.
     * 
     * @return
     *     possible object is
     *     {@link FS }
     *     
     */
    public FS getFs() {
        return fs;
    }

    /**
     * Sets the value of the fs property.
     * 
     * @param value
     *     allowed object is
     *     {@link FS }
     *     
     */
    public void setFs(FS value) {
        this.fs = value;
    }

    /**
     * Gets the value of the java property.
     * 
     * @return
     *     possible object is
     *     {@link JAVA }
     *     
     */
    public JAVA getJava() {
        return java;
    }

    /**
     * Sets the value of the java property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAVA }
     *     
     */
    public void setJava(JAVA value) {
        this.java = value;
    }

    /**
     * Gets the value of the ok property.
     * 
     * @return
     *     possible object is
     *     {@link ACTIONTRANSITION }
     *     
     */
    public ACTIONTRANSITION getOk() {
        return ok;
    }

    /**
     * Sets the value of the ok property.
     * 
     * @param value
     *     allowed object is
     *     {@link ACTIONTRANSITION }
     *     
     */
    public void setOk(ACTIONTRANSITION value) {
        this.ok = value;
    }

    /**
     * Gets the value of the error property.
     * 
     * @return
     *     possible object is
     *     {@link ACTIONTRANSITION }
     *     
     */
    public ACTIONTRANSITION getError() {
        return error;
    }

    /**
     * Sets the value of the error property.
     * 
     * @param value
     *     allowed object is
     *     {@link ACTIONTRANSITION }
     *     
     */
    public void setError(ACTIONTRANSITION value) {
        this.error = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getAny() {
        return any;
    }

    /**
     * Sets the value of the any property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setAny(Object value) {
        this.any = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the cred property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCred() {
        return cred;
    }

    /**
     * Sets the value of the cred property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCred(String value) {
        this.cred = value;
    }

    /**
     * Gets the value of the retryMax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRetryMax() {
        return retryMax;
    }

    /**
     * Sets the value of the retryMax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRetryMax(String value) {
        this.retryMax = value;
    }

    /**
     * Gets the value of the retryInterval property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRetryInterval() {
        return retryInterval;
    }

    /**
     * Sets the value of the retryInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRetryInterval(String value) {
        this.retryInterval = value;
    }

}
