//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.27 at 05:15:54 PM GMT+05:30 
//


package org.apache.ivory.oozie.workflow;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FS complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FS">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="delete" type="{uri:oozie:workflow:0.3}DELETE" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="mkdir" type="{uri:oozie:workflow:0.3}MKDIR" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="move" type="{uri:oozie:workflow:0.3}MOVE" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="chmod" type="{uri:oozie:workflow:0.3}CHMOD" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FS", propOrder = {
    "delete",
    "mkdir",
    "move",
    "chmod"
})
public class FS {

    protected List<DELETE> delete;
    protected List<MKDIR> mkdir;
    protected List<MOVE> move;
    protected List<CHMOD> chmod;

    /**
     * Gets the value of the delete property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the delete property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDelete().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DELETE }
     * 
     * 
     */
    public List<DELETE> getDelete() {
        if (delete == null) {
            delete = new ArrayList<DELETE>();
        }
        return this.delete;
    }

    /**
     * Gets the value of the mkdir property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the mkdir property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMkdir().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MKDIR }
     * 
     * 
     */
    public List<MKDIR> getMkdir() {
        if (mkdir == null) {
            mkdir = new ArrayList<MKDIR>();
        }
        return this.mkdir;
    }

    /**
     * Gets the value of the move property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the move property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMove().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MOVE }
     * 
     * 
     */
    public List<MOVE> getMove() {
        if (move == null) {
            move = new ArrayList<MOVE>();
        }
        return this.move;
    }

    /**
     * Gets the value of the chmod property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the chmod property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getChmod().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CHMOD }
     * 
     * 
     */
    public List<CHMOD> getChmod() {
        if (chmod == null) {
            chmod = new ArrayList<CHMOD>();
        }
        return this.chmod;
    }

}
