//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.27 at 05:15:54 PM GMT+05:30 
//


package org.apache.ivory.oozie.workflow;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WORKFLOW-APP complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WORKFLOW-APP">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="credentials" type="{uri:oozie:workflow:0.3}CREDENTIALS" minOccurs="0"/>
 *         &lt;element name="start" type="{uri:oozie:workflow:0.3}START"/>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element name="decision" type="{uri:oozie:workflow:0.3}DECISION"/>
 *           &lt;element name="fork" type="{uri:oozie:workflow:0.3}FORK"/>
 *           &lt;element name="join" type="{uri:oozie:workflow:0.3}JOIN"/>
 *           &lt;element name="kill" type="{uri:oozie:workflow:0.3}KILL"/>
 *           &lt;element name="action" type="{uri:oozie:workflow:0.3}ACTION"/>
 *         &lt;/choice>
 *         &lt;element name="end" type="{uri:oozie:workflow:0.3}END"/>
 *         &lt;any namespace='uri:oozie:sla:0.1' minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{uri:oozie:workflow:0.3}IDENTIFIER" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WORKFLOW-APP", propOrder = {
    "credentials",
    "start",
    "decisionOrForkOrJoin",
    "end",
    "any"
})
public class WORKFLOWAPP {

    protected CREDENTIALS credentials;
    @XmlElement(required = true)
    protected START start;
    @XmlElements({
        @XmlElement(name = "kill", type = KILL.class),
        @XmlElement(name = "action", type = ACTION.class),
        @XmlElement(name = "join", type = JOIN.class),
        @XmlElement(name = "decision", type = DECISION.class),
        @XmlElement(name = "fork", type = FORK.class)
    })
    protected List<Object> decisionOrForkOrJoin;
    @XmlElement(required = true)
    protected END end;
    @XmlAnyElement(lax = true)
    protected Object any;
    @XmlAttribute(required = true)
    protected String name;

    /**
     * Gets the value of the credentials property.
     * 
     * @return
     *     possible object is
     *     {@link CREDENTIALS }
     *     
     */
    public CREDENTIALS getCredentials() {
        return credentials;
    }

    /**
     * Sets the value of the credentials property.
     * 
     * @param value
     *     allowed object is
     *     {@link CREDENTIALS }
     *     
     */
    public void setCredentials(CREDENTIALS value) {
        this.credentials = value;
    }

    /**
     * Gets the value of the start property.
     * 
     * @return
     *     possible object is
     *     {@link START }
     *     
     */
    public START getStart() {
        return start;
    }

    /**
     * Sets the value of the start property.
     * 
     * @param value
     *     allowed object is
     *     {@link START }
     *     
     */
    public void setStart(START value) {
        this.start = value;
    }

    /**
     * Gets the value of the decisionOrForkOrJoin property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the decisionOrForkOrJoin property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDecisionOrForkOrJoin().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link KILL }
     * {@link ACTION }
     * {@link JOIN }
     * {@link DECISION }
     * {@link FORK }
     * 
     * 
     */
    public List<Object> getDecisionOrForkOrJoin() {
        if (decisionOrForkOrJoin == null) {
            decisionOrForkOrJoin = new ArrayList<Object>();
        }
        return this.decisionOrForkOrJoin;
    }

    /**
     * Gets the value of the end property.
     * 
     * @return
     *     possible object is
     *     {@link END }
     *     
     */
    public END getEnd() {
        return end;
    }

    /**
     * Sets the value of the end property.
     * 
     * @param value
     *     allowed object is
     *     {@link END }
     *     
     */
    public void setEnd(END value) {
        this.end = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getAny() {
        return any;
    }

    /**
     * Sets the value of the any property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setAny(Object value) {
        this.any = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
