//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.03 at 12:41:24 PM GMT+05:30 
//


package org.apache.ivory.entity.v0.cluster;

import java.util.Map;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import org.apache.ivory.entity.v0.Entity;
import org.apache.ivory.entity.v0.cluster.adapter.InterfacesMapAdapter;
import org.apache.ivory.entity.v0.cluster.adapter.LocationsMapAdapter;
import org.apache.ivory.entity.v0.cluster.adapter.PropertiesMapAdapter;


/**
 * <p>Java class for cluster complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="cluster">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="interfaces" type="{uri:ivory:cluster:0.1}interfaces"/>
 *         &lt;element name="locations" type="{uri:ivory:cluster:0.1}locations"/>
 *         &lt;element name="properties" type="{uri:ivory:cluster:0.1}properties"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{uri:ivory:cluster:0.1}IDENTIFIER" />
 *       &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="colo" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "cluster", propOrder = {
    "interfaces",
    "locations",
    "properties"
})
@XmlRootElement(name="cluster")
public class Cluster extends Entity{

	@XmlJavaTypeAdapter(InterfacesMapAdapter.class)
    @XmlElement(required = true)
    protected Map<Interfacetype,Interface> interfaces;
	@XmlJavaTypeAdapter(LocationsMapAdapter.class)
    @XmlElement(required = true)
    protected Map<String,Location> locations;
	@XmlJavaTypeAdapter(PropertiesMapAdapter.class)
    @XmlElement(required = true)
    protected Map<String,Property> properties;
    @XmlAttribute
    protected String name;
    @XmlAttribute
    protected String description;
    @XmlAttribute
    protected String colo;

    /**
     * Gets the value of the interfaces property.
     * 
     * @return
     *     possible object is
     *     {@link Interfaces }
     *     
     */
    public Map<Interfacetype,Interface> getInterfaces() {
        return interfaces;
    }

    /**
     * Sets the value of the interfaces property.
     * 
     * @param value
     *     allowed object is
     *     {@link Interfaces }
     *     
     */
    public void setInterfaces(Map<Interfacetype,Interface> value) {
        this.interfaces = value;
    }

    /**
     * Gets the value of the locations property.
     * 
     * @return
     *     possible object is
     *     {@link Locations }
     *     
     */
    public Map<String,Location> getLocations() {
        return locations;
    }

    /**
     * Sets the value of the locations property.
     * 
     * @param value
     *     allowed object is
     *     {@link Locations }
     *     
     */
    public void setLocations(Map<String,Location> value) {
        this.locations = value;
    }

    /**
     * Gets the value of the properties property.
     * 
     * @return
     *     possible object is
     *     {@link Properties }
     *     
     */
    public Map<String,Property> getProperties() {
        return properties;
    }

    /**
     * Sets the value of the properties property.
     * 
     * @param value
     *     allowed object is
     *     {@link Properties }
     *     
     */
    public void setProperties(Map<String,Property> value) {
        this.properties = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the colo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColo() {
        return colo;
    }

    /**
     * Sets the value of the colo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColo(String value) {
        this.colo = value;
    }

    @Override
    public String[] getImmutableProperties() {
        String[] props = {"name"};
        return props;
    }
}
