//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.03 at 12:41:24 PM GMT+05:30 
//


package org.apache.ivory.entity.v0.cluster;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for interfacetype.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="interfacetype">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="readonly"/>
 *     &lt;enumeration value="write"/>
 *     &lt;enumeration value="execute"/>
 *     &lt;enumeration value="workflow"/>
 *     &lt;enumeration value="messaging"/>
 *     &lt;enumeration value="registry"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "interfacetype")
@XmlEnum
public enum Interfacetype {

    @XmlEnumValue("readonly")
    READONLY("readonly"),
    @XmlEnumValue("write")
    WRITE("write"),
    @XmlEnumValue("execute")
    EXECUTE("execute"),
    @XmlEnumValue("workflow")
    WORKFLOW("workflow"),
    @XmlEnumValue("messaging")
    MESSAGING("messaging"),
    @XmlEnumValue("registry")
    REGISTRY("registry");
    private final String value;

    Interfacetype(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Interfacetype fromValue(String v) {
        for (Interfacetype c: Interfacetype.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
