//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.08 at 10:28:42 AM GMT+05:30 
//


package org.apache.airavat.oozie.coordinator;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DATAIN complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DATAIN">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="instance" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *         &lt;sequence>
 *           &lt;element name="start-instance" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="end-instance" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;/sequence>
 *       &lt;/choice>
 *       &lt;attribute name="name" use="required" type="{uri:oozie:coordinator:0.1}IDENTIFIER" />
 *       &lt;attribute name="dataset" use="required" type="{uri:oozie:coordinator:0.1}IDENTIFIER" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DATAIN", propOrder = {
    "instance",
    "startInstance",
    "endInstance"
})
public class DATAIN {

    protected List<String> instance;
    @XmlElement(name = "start-instance")
    protected String startInstance;
    @XmlElement(name = "end-instance")
    protected String endInstance;
    @XmlAttribute(required = true)
    protected String name;
    @XmlAttribute(required = true)
    protected String dataset;

    /**
     * Gets the value of the instance property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the instance property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInstance().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getInstance() {
        if (instance == null) {
            instance = new ArrayList<String>();
        }
        return this.instance;
    }

    /**
     * Gets the value of the startInstance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartInstance() {
        return startInstance;
    }

    /**
     * Sets the value of the startInstance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartInstance(String value) {
        this.startInstance = value;
    }

    /**
     * Gets the value of the endInstance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndInstance() {
        return endInstance;
    }

    /**
     * Sets the value of the endInstance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndInstance(String value) {
        this.endInstance = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the dataset property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataset() {
        return dataset;
    }

    /**
     * Sets the value of the dataset property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataset(String value) {
        this.dataset = value;
    }

}
