//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.27 at 05:15:55 PM GMT+05:30 
//


package org.apache.ivory.oozie.bundle;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BUNDLE-APP complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BUNDLE-APP">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="controls" type="{uri:oozie:bundle:0.1}CONTROLS" minOccurs="0"/>
 *         &lt;element name="coordinator" type="{uri:oozie:bundle:0.1}COORDINATOR" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{uri:oozie:bundle:0.1}IDENTIFIER" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BUNDLE-APP", propOrder = {
    "controls",
    "coordinator"
})
public class BUNDLEAPP {

    protected CONTROLS controls;
    @XmlElement(required = true)
    protected List<COORDINATOR> coordinator;
    @XmlAttribute(required = true)
    protected String name;

    /**
     * Gets the value of the controls property.
     * 
     * @return
     *     possible object is
     *     {@link CONTROLS }
     *     
     */
    public CONTROLS getControls() {
        return controls;
    }

    /**
     * Sets the value of the controls property.
     * 
     * @param value
     *     allowed object is
     *     {@link CONTROLS }
     *     
     */
    public void setControls(CONTROLS value) {
        this.controls = value;
    }

    /**
     * Gets the value of the coordinator property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the coordinator property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCoordinator().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link COORDINATOR }
     * 
     * 
     */
    public List<COORDINATOR> getCoordinator() {
        if (coordinator == null) {
            coordinator = new ArrayList<COORDINATOR>();
        }
        return this.coordinator;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
