//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.28 at 10:55:57 AM PDT 
//


package org.apache.falcon.entity.v0.feed;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.apache.falcon.entity.v0.Frequency;


/**
 * 
 *                 late-arrival specifies the cut-off period till which the feed is
 *                 expected to arrive late and should be honored be processes referring
 *                 to it as input
 *                 feed by rerunning the instances in case
 *                 the data arrives late with in a cut-off period.
 *                 The cut-off period is specified by expression
 *                 frequency(times), ex: if the feed
 *                 can arrive late
 *                 upto 8 hours then late-arrival's cut-off="hours(8)"
 *             
 * 
 * <p>Java class for late-arrival complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="late-arrival">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="cut-off" use="required" type="{uri:falcon:feed:0.1}frequency-type" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "late-arrival")
public class LateArrival {

    @XmlAttribute(name = "cut-off", required = true)
    @XmlJavaTypeAdapter(Adapter1 .class)
    protected Frequency cutOff;

    /**
     * Gets the value of the cutOff property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Frequency getCutOff() {
        return cutOff;
    }

    /**
     * Sets the value of the cutOff property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCutOff(Frequency value) {
        this.cutOff = value;
    }

}
