//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.28 at 10:55:57 AM PDT 
//


package org.apache.falcon.entity.v0.process;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.apache.falcon.entity.v0.Frequency;


/**
 * <p>Java class for late-process complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="late-process">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="late-input" type="{uri:falcon:process:0.1}late-input" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="policy" use="required" type="{uri:falcon:process:0.1}policy-type" />
 *       &lt;attribute name="delay" use="required" type="{uri:falcon:process:0.1}frequency-type" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "late-process", propOrder = {
    "lateInputs"
})
public class LateProcess {

    @XmlElement(name = "late-input", required = true)
    protected List<LateInput> lateInputs;
    @XmlAttribute(name = "policy", required = true)
    protected PolicyType policy;
    @XmlAttribute(name = "delay", required = true)
    @XmlJavaTypeAdapter(Adapter1 .class)
    protected Frequency delay;

    /**
     * Gets the value of the lateInputs property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the lateInputs property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLateInputs().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LateInput }
     * 
     * 
     */
    public List<LateInput> getLateInputs() {
        if (lateInputs == null) {
            lateInputs = new ArrayList<LateInput>();
        }
        return this.lateInputs;
    }

    /**
     * Gets the value of the policy property.
     * 
     * @return
     *     possible object is
     *     {@link PolicyType }
     *     
     */
    public PolicyType getPolicy() {
        return policy;
    }

    /**
     * Sets the value of the policy property.
     * 
     * @param value
     *     allowed object is
     *     {@link PolicyType }
     *     
     */
    public void setPolicy(PolicyType value) {
        this.policy = value;
    }

    /**
     * Gets the value of the delay property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Frequency getDelay() {
        return delay;
    }

    /**
     * Sets the value of the delay property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDelay(Frequency value) {
        this.delay = value;
    }

}
